### ISSUE TITLE
Need to be able to specify amount of RAM at runtime

### ISSUE THREAD

**Issue by j-fray** [strimmcode/strimm#2]
Currently the amount of RAM STRÏMM uses is set in /package/launcher.cpp, meaning it cannot be changed after STRÏMM is compiled into an executable. RAM (heap size) can be specified to the VM in commands using -Xms and -Xmx. Note that you cannot specify or change VM command settings at runtime

Potential solution will be:
- Creating a buffer object who's RAM can be specified via a setting. This new buffer will store all acquisition data.
- Modify data store actors so they add their data to this buffer
- Ensure that the -Xms and -Xmx setting are not exceeded by this new buffer's size. Make sure that -Xms and -Xmx are set sufficiently high in launcher.cpp

**Comment by strimmcode** [comment]
Closing as bug was part of old code
