### ISSUE TITLE
Data from multiple ROIs is "multiplexed"

### ISSUE THREAD

**Issue by j-fray** [strimmcode/strimm#4]
When a camera feed has more than one ROI, ROI data is multiplexed. This means if there are 3 ROIs the data will look like [ROI1 data point 1, ROI2 data point 1, ROI3 data point 1, ROI1 data point 2, ROI2 data point 2, ROI3 data point 2...]

Although the Python script to extract data from H5 file can handle this, we would normally expect each ROI to have it's own dataset.

This will involve modifying code in the TraceDataStoreActor, but also where the ROI data points are generated in thefirst place, which will likely be in ExperimentStream.kt but possibly also the AverageROI acquisition method in AcquisitionMethodService.kt

**Comment by strimmcode** [comment]
Issue has been fixed as part of new protocol CSV format (developed by Terry)
